services:
  mongo:
    image: mongo
    restart: on-failure
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - pbautomacoes
    healthcheck:
      test: [ "CMD-SHELL", "mongosh -u \"$${MONGO_INITDB_ROOT_USERNAME}\" -p \"$${MONGO_INITDB_ROOT_PASSWORD}\" --authenticationDatabase $${MONGO_AUTH_SOURCE} --eval \"db.adminCommand({ ping: 1 })\"" ]
      interval: 10s
      timeout: 5s
      retries: 5


  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - pbautomacoes

  mongo-express:
    image: mongo-express
    restart: on-failure
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
      ME_CONFIG_BASICAUTH: 'false'
    ports:
      - 8081:8081
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - pbautomacoes

networks:
  pbautomacoes:
    driver: bridge